version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=shyam
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/data/postgres
volumes:
  db:
    driver: local