server:
  port: 8080
  error:
    include-message: always


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: shyam
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
        format_sql: true
      show-sql: false
    main:
      web-application-type: servlet

